[CV-5925]: fix java.lang.NoSuchMethodError: javax.ws.rs.core.Application.getProperties() Ljava/util/Map; exception Remove jsr311-api which is This is the official spec jar for the JAX-RS 1.x line and dropwizard is using 2.x now